### ISSUE TITLE
Html language veranderen naar NL

### ISSUE THREAD

**Issue by Akikosophia** [Anna-Kyra/the-startup-responsive-interactieve-website#10]
je kunt de veranderen naar nederlands :) <html lang="nl">

Hieronder de link
https://github.com/Anna-Kyra/the-startup-responsive-interactieve-website/blob/f57e6f8da63b2bedb6471794daf229298f90211d/index.html#L2

**Comment by Anna-Kyra** [comment]
Bedankt, maar de website is in het engels :D
