### ISSUE TITLE
HTML Validator  stray end tags

### ISSUE THREAD

**Issue by KaanKalmi** [Anna-Kyra/the-startup-responsive-interactieve-website#11]
![image](https://github.com/Anna-Kyra/the-startup-responsive-interactieve-website/assets/144000125/4b8fcef4-2118-4742-8fbf-407a284cba0c)

Ik zie dat je veel van deze errors hebt met stray ending tags, kijk er ff naar je hebt namelijk echt abnormaal veel van deze problemen, met stray div endings, anchor element endings etc.

**Comment by Anna-Kyra** [comment]
Gefixed, thx voor het checken :)
