### ISSUE TITLE
Stray tags in html

### ISSUE THREAD

**Issue by smolgeorgie** [Anna-Kyra/the-startup-responsive-interactieve-website#12]
Je hebt een stray tag in je html, ik zou deze eruit halen. Je kan erdoor overzicht verliezen. 

stray div: [stray div html](https://github.com/Anna-Kyra/the-startup-responsive-interactieve-website/blob/f57e6f8da63b2bedb6471794daf229298f90211d/index.html#L89)

stray a: [stray a html](https://github.com/Anna-Kyra/the-startup-responsive-interactieve-website/blob/f57e6f8da63b2bedb6471794daf229298f90211d/index.html#L173-L199)

hierbij heb je een dubbele afsluiten van de </a>

**Comment by Anna-Kyra** [comment]
Gefixed, thx voor het checken :)
