### ISSUE TITLE
HTML tabs

### ISSUE THREAD

**Issue by lemuelmgsn** [Anna-Kyra/the-startup-responsive-interactieve-website#6]
https://github.com/Anna-Kyra/the-startup-responsive-interactieve-website/blob/bc9a44f86bf9c0e67719db8acd5798393253e51b/index.html#L115-L145

Je hebt een goede HTML structuur! alleen denk ik dat je je code wat meer naar links kan verplaatsen want nu heb je daar best veel ruimte wat je niet gebruikt.

**Comment by Anna-Kyra** [comment]
komt door een extension, maar snap dat het verwarrend eruit ziet. Ik ga hem verwijderen
