### ISSUE TITLE
De tekst voor de footer

### ISSUE THREAD

**Issue by Pink-Mallow** [Anna-Kyra/the-startup-responsive-interactieve-website#8]
Het stukje waar er staat "Interested in our work?...." mag het ietsje verder van de footer staan. Ik weet niet of het de bedoeling was om het zo dichtbij de footer te zetten, maar als het niet zo is geef het wat afstand want ik dacht bijna er moest iets meer komen en dat de footer in de weg staat. (Als je snapt wat ik bedoel)

![image](https://github.com/Anna-Kyra/the-startup-responsive-interactieve-website/assets/144671961/549c7f28-f474-4dd1-9439-6a12614cf490)

**Comment by Anna-Kyra** [comment]
fixed tot nu toe (voor mobile)
