### ISSUE TITLE
Ruimte tussen content

### ISSUE THREAD

**Issue by Pink-Mallow** [Anna-Kyra/the-startup-responsive-interactieve-website#9]
Ik vind het heel leuk hoe je deze dingen hebt gemaakt (posts?), doet me denken aan nieuws articelen. 

Maar een tip (ik weet niet of je het zo moest doen) misschien die foto en tekst, dus het hele opstelling van zo'n stukje misschien wat kleiner en wat ruimte ertussen creëren met de hand van margin en wat padding. Het voelt zo overweldigend dat alles zo groot is en dat er weinig ruimte is tussen sommige contents.

![image](https://github.com/Anna-Kyra/the-startup-responsive-interactieve-website/assets/144671961/ea81de4a-b680-470f-aba1-10b497014da5)

**Comment by Anna-Kyra** [comment]
gefixed, heb nu `1rem` ruimte gemaakt in plaats van `.5rem`
